version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/conf:/config_files
    restart: always
    depends_on:
      - prometheus
    privileged: true

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config:/mnt/config
    command:
      - '-config.file=/mnt/config/loki-config.yaml'
    restart: always

  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/config:/mnt/config
      - ./../logs:/mnt/logs
    command:
      - '-config.file=/mnt/config/promtail-config.yaml'
    depends_on:
      - loki
    restart: always

  tempo:
    image: grafana/tempo
    container_name: tempo
    ports:
      - "3200:3200"
    volumes:
      - ./tempo/config:/mnt/config
    command:
      - '-config.file=/mnt/config/tempo.yaml'
    restart: always

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always
