auth_enabled: false  # 인증 비활성화

server:
  http_listen_port: 3100  # Loki 서버가 3100 포트에서 HTTP 요청 수신

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory  # 인메모리 키-값 저장소 사용
      replication_factor: 1  # 복제 계수 설정
  chunk_idle_period: 5m  # 청크 비활성 기간 설정
  chunk_retain_period: 30s  # 청크 유지 기간 설정

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h  # 인덱스 주기를 24시간으로 설정

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache

  filesystem:
    directory: /loki/chunks  # 파일 시스템 청크 디렉토리 설정

limits_config:
  reject_old_samples: true  # 오래된 샘플 거부
  reject_old_samples_max_age: 168h  # 오래된 샘플 최대 허용 연령
  allow_structured_metadata: false  # 구조화된 메타데이터 허용 비활성화

table_manager:
  retention_deletes_enabled: true  # 보존 삭제 활성화
  retention_period: 168h  # 보존 기간 설정

compactor:
  working_directory: /loki/compactor  # 유효한 작업 디렉토리 설정

common:
  path_prefix: /loki  # 공통 경로 접두사 설정
