management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # ???? ??? ??? 100%? ?????.
  endpoints:
    web:
      exposure:
        include: prometheus  # Prometheus ?????? ?????.
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true  # HTTP ?? ??? ?? ????? ????? ??????.

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"  # traceId? spanId? ??? ?? ??? ?????.