application:
  id: 'HyperX_API_App'
  title: 'API Application'
  version: 1.0.0

spring:
  profiles:
    # process env (local,dev,prod) 설정
    # active: dev
    # core 설정 연동
    include: core

  servlet:
    multipart:
      max-file-size: 10MB

  config:
    import:
      - classpath:application-prometheus.properties
      - classpath:application-apidoc.yml
      - classpath:application-logger.properties
      - classpath:application-jwt.yml

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true


# 로컬 환경 설정
---

spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:application-r2dbc-local.properties

# 개발계 환경 설정
---

spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:application-r2dbc-dev.properties

# 운영계 환경 설정
---

spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:application-r2dbc-prod.properties