version: '3.7'

services:
  tempo:
    image: grafana/tempo:latest
    ports:
      - "4317:4317"
      - "14268:14268"
      - "9411:9411"
    networks:
      - observability
    environment:
      - LOG_LEVEL=debug

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    networks:
      - observability
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  observability:
    driver: bridge
