server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
        thrift_http:

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

compactor:
  compaction:
    compacted_block_retention: 24h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
