application:
  id: 'HyperX_Batch_App'
  title: 'Batch Application'
  version: 1.0.0

server:
  port: 8001

spring:
  profiles:
    # process env (local,dev,prod) 설정
    # active: dev
    # core 설정 연동
    include: core,jpa

  servlet:
    multipart:
      max-file-size: 10MB

  config:
    import:
      - classpath:application-prometheus.properties
      - classpath:application-apidoc.properties
      - classpath:application-logger.properties
      - classpath:application-jwt.yml
      - classpath:application-batch.yml
      - classpath:application-kafka.yml

