spring:
  config:
    import:
      - classpath:application-mail.yml

# 로컬 환경 설정
---

spring:
  config:
    activate:
      on-profile: local
process.env: local

# 개발계 환경 설정
---

spring:
  config:
    activate:
      on-profile: dev
process.env: development

# 운영계 환경 설정
---

spring:
  config:
    activate:
      on-profile: prod
process.env: production